<?php

use MageHx\MahxCheckout\ViewModel\HxAttributesRenderer;
use MageHx\MahxCheckout\Block\PaymentRenderer;
use MageHx\MahxCheckout\Data\PaymentMethodData;
use MageHx\MahxCheckoutOffline\ViewModel\PaymentMethodInstruction;

/** @var PaymentRenderer $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $eUrl */
/** @var Closure $viewModelProvider */
/** @var PaymentMethodData $payment */
/** @var PaymentMethodInstruction $instructionVm */
/** @var HxAttributesRenderer $hxAttrRenderer */

$payment = $block->getPaymentData();
$instructionVm = $viewModelProvider(PaymentMethodInstruction::class);
$hxAttrRenderer = $viewModelProvider(HxAttributesRenderer::class);
?>
<div id="<?= $eHtmlAttr($payment->code) ?>" class="form-control">
    <label class="label cursor-pointer justify-start space-x-2">
        <input
            type="radio" class="radio checked:bg-neutral" name="payment_method"
            value="<?= $eHtmlAttr($payment->code) ?>"
            id="payment_form_method__<?= $eHtmlAttr($payment->code) ?>"
            <?= $block->isSelected() ? 'checked="checked"': '' ?>
            <?= $hxAttrRenderer->hxBuilder()
                ->post('mahxcheckout/form/paymentMethodPost')
                ->target('#payment-methods-section')
                ->indicator('.save-payment-loader')
                ->swapOuterHTML()
                ->render()
            ?>
        />
        <span class="label-text"><?= $eHtml($payment->title) ?></span>
    </label>
    <?php if ($block->isSelected()): ?>
        <div class="ml-4 text-sm my-4">
            <?= $instructionVm->get($payment) ?>
        </div>
    <?php endif; ?>
</div>
