<?php declare(strict_types=1);

use MageHx\MageTemplateUtils\Model\Esc;
use MageHx\MageTemplateUtils\Model\ViewModelProvider;
use MageHx\MahxCheckout\ViewModel\DesignThemeInfo;
use MageHx\MahxCheckout\ViewModel\HxAttributesRenderer;
use MageHx\MahxCheckout\Block\PaymentRenderer;
use MageHx\MahxCheckout\Data\PaymentMethodData;
use MageHx\MahxCheckoutOffline\ViewModel\PurchaseOrder;

/** @var PaymentRenderer $block */
/** @var Esc $esc */
/** @var ViewModelProvider $viewModelProvider */
/** @var PaymentMethodData $payment */

$payment = $block->getPaymentData();
$viewModel = $viewModelProvider->get(PurchaseOrder::class);
$hxAttrRenderer = $viewModelProvider->get(HxAttributesRenderer::class);
$designThemeInfo = $viewModelProvider->get(DesignThemeInfo::class);
?>
<div id="<?= $esc->htmlAttr($payment->code) ?>" class="payment-method form-control">
    <div class="payment-method-title flex items-center gap-x-1">
        <input
            type="radio" class="radio checked:bg-neutral" name="payment_method"
            value="<?= $esc->htmlAttr($payment->code) ?>"
            id="payment_method_<?= $esc->htmlAttr($payment->code) ?>"
            <?= $block->isSelected() ? 'checked="checked"': '' ?>
            <?= $hxAttrRenderer->hxBuilder()
                ->post('mahxcheckout/form/paymentMethodPost')
                ->target('#payment-methods-section')
                ->indicator('.save-payment-loader')
                ->swapOuterHTML()
                ->render()
            ?>
        />
        <label for="payment_method_<?= $esc->htmlAttr($payment->code) ?>" class="label cursor-pointer justify-start space-x-2">
            <span class="label-text"><?= $esc->html($payment->title) ?></span>
        </label>
    </div>
    <?php if ($block->isSelected()): ?>
        <?php if ($designThemeInfo->isMagentoTheme()): ?>
        <style>.po-content { width: 40%;}</style>
        <?php endif; ?>
        <div class="payment-content po-content fieldset ml-4 text-sm my-4">
            <?= $viewModel->renderPONumberField() ?>
        </div>
    <?php endif; ?>
</div>
